### ISSUE TITLE
TypeError: postgrator.setConfig is not a function

### ISSUE THREAD

**Issue by jsphkm** [rickbergfalk/postgrator#118]
I'm running postgrator in node as instructed:

```
postgrator.setConfig(migrationConfig);
postgrator.migrate('002', (err, migrations) => {
  if (err) {
    console.error(err);
  } else {
    console.log(migrations);
  }
  postgrator.endConnection();
});
```

The migrationConfig toggles between connection string and host/database/username/pass objects between environments.

With the postgrator-cli, migrating manually works, e.g. `yarn run migrate -- 2`

However, when running the node instance, I'm met with this error:
```
postgrator.setConfig(migrationConfig);
           ^

TypeError: postgrator.setConfig is not a function
```

I've made sure that the `postgrator` is installed as a dependency, as well as a `postgrator-cli` in the devDependencies.

In production on Heroku, the instance fails with the same error:
```
postgrator.setConfig(migrationConfig);
^
TypeError: postgrator.setConfig is not a function
```

Console logging postgrator shows that it's defined and is a function, `[Function: Postgrator]`
And, console logging postgrator's property names in node shows this:
```
const postgrator = require('postgrator');
console.log(Object.getOwnPropertyNames(postgrator));

// Output
[ 'length', 'prototype', 'name' ]
```

What's causing this issue?

**Comment by rickbergfalk** [comment]
Hi @jsphkm I think you might be using the old API. I think it was version 3 that things changed to something like 

```js
const Postgrator = require('postgrator')

const postgrator = new Postgrator(config)

// Migrate to specific version
postgrator
  .migrate('002')
  .then((appliedMigrations) => console.log(appliedMigrations))
  .catch((error) => {
    console.log(error)
    // Because migrations prior to the migration with error would have run
    // error object is decorated with appliedMigrations
    console.log(error.appliedMigrations) // array of migration objects
  })
```

**Comment by jsphkm** [comment]
Hello Rick, thanks for the response.  I've deployed to Heroku on server after changing the code as you suggested.  Now I'm seeing this response:
```
2020-10-17T01:03:07.435662+00:00 app[web.1]: [nodemon] 2.0.4
2020-10-17T01:03:07.450817+00:00 app[web.1]: [nodemon] to restart at any time, enter `rs`
2020-10-17T01:03:07.450828+00:00 app[web.1]: [nodemon] watching path(s): *.*
2020-10-17T01:03:07.450829+00:00 app[web.1]: [nodemon] watching extensions: js,mjs,json
2020-10-17T01:03:07.451005+00:00 app[web.1]: [nodemon] starting `node src/server.js`
2020-10-17T01:03:07.952788+00:00 app[web.1]: Express is listening on port 28304
2020-10-17T01:03:07.995995+00:00 app[web.1]: Unhandled rejection Error: self signed certificate
2020-10-17T01:03:07.995996+00:00 app[web.1]: at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
2020-10-17T01:03:07.995997+00:00 app[web.1]: at TLSSocket.emit (events.js:314:20)
2020-10-17T01:03:07.995998+00:00 app[web.1]: at TLSSocket._finishInit (_tls_wrap.js:937:8)
2020-10-17T01:03:07.995998+00:00 app[web.1]: at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
2020-10-17T01:03:08.209678+00:00 heroku[web.1]: State changed from starting to up
```

This is actually what I saw before if I ran with `postgrator-cli`, and manually migrated with production env.  So now the original issue seems to be fixed?

I'm not sure what this message indicates now though.

**Comment by rickbergfalk** [comment]
It looks like you have a different issue related to the self signed cert not being accepted. You can set an environment variable to ignore this, though it is generally not advised to do so in production https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain?rq=1
